version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - "fishbrain/web-developers"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "fishbrain/web-developers"
