language: node_js
node_js:
  - stable

jobs:
  include:
    - stage: npm release
      node_js: stable
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: erik.gustav.dalen@gmail.com
        api_key:
          secure: VcPKQ9ZboQUjlGz6bM8kMV8r5GUB0ADkCfzP0Sqxn0XcJmGdUxKokkU+DVOesxFIaE8kgzhE8T3Nrjij7T0i++IX0iwkt9Ii1O2Jtr+gKLue2U6Ne4yOGA+prh3U6lYB8UNGScbmwnIKQqM1TgUhOtXrsVZwPdOQJwxyNZDThDZVzFXUMllpd1cfrIZuLi1JkirqG+rQeQxxOjVI0wMtNiYmWw0fcbbF96wN9i6zXaZiilDkpLd70UkILKEtagg34Q4er3n+jM0GwYFHsqgsp3hnOhC8Kk0hmD14F8iWerY6197IImZuOdtsJdpj/LDWvuoTa1wkn8r/2I2N5gbiP55+Zgt95YvihqFg5eFrv6cN9DqOOtXODh0Ibi6/Z4DtMtYCT1+RDafcC52sLIXxkjxkMMRN9Zn+6Fqy+ByR7qWPrtpwONT6P7HBG6xslQAcM445qpsKYXncnOPWeOxi7uuDccm0Ipf74SW4Ntxct+mwUVJ+RXoqoIQjrSLcQOvUIPclTiASfOD9+mopoU5A1PGDWXJhLVkv6ejSUi/xu7PZxqLuC/vlf7oz054s0/Gb3/CCP3a2Y4OnqF/8vLZqJ+yrIdjW4gGZ9ayOH24AqRNtyeLG4w60Gb4loa2A145Ze2nE1bZ6md0hqmt6BaHDju471qllzjt9tt9OOOEd6Uc=
        on:
          repo: fishbrain/eslint-config-fishbrain-base
          branch: master
